"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://tibia.fandom.com/wiki/Main_Page
  name = tibiawiki

Please do not commit this to the Git repository!
"""
from pywikibot import family


class TibiaWikiFamily(family.Family):  # noqa: D101

    name = 'tibiawiki'
    langs = {
        'en': 'tibia.fandom.com',
    }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
